<?php
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AttendanceController;
use App\Http\Controllers\Api\ExamResultController;
use App\Http\Controllers\Api\ExamManagementController;
use App\Http\Controllers\Api\QuestionBankController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\PluginStoreController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\StudentController;
use App\Http\Controllers\Api\WorksheetController;
use Illuminate\Support\Facades\Route;
Route::post('/auth/register', [AuthController::class, 'register']);
Route::post('/auth/login', [AuthController::class, 'login']);
Route::post('/auth/admin/login', fn (\Illuminate\Http\Request $request, AuthController $controller) => $controller->loginAsRole($request, 'admin'));
Route::post('/auth/parent/login', fn (\Illuminate\Http\Request $request, AuthController $controller) => $controller->loginAsRole($request, 'parent'));
Route::post('/auth/student/login', fn (\Illuminate\Http\Request $request, AuthController $controller) => $controller->loginAsRole($request, 'student'));
Route::middleware('auth:sanctum')->group(function () {
    Route::get('/auth/me', [AuthController::class, 'me']);
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::apiResource('students', StudentController::class)->only(['index','store','show','update','destroy']);
    Route::get('/students/{student}/qr', [StudentController::class, 'qr']);
    Route::apiResource('worksheets', WorksheetController::class)->only(['index','store','show']);
    Route::post('/worksheets/{worksheet}/assign', [WorksheetController::class, 'assign']);
    Route::post('/assignments/{assignment}/submit', [WorksheetController::class, 'submit']);
    Route::apiResource('attendance', AttendanceController::class)->only(['index','store','update','destroy']);
    Route::post('/attendance/scan', [AttendanceController::class, 'scan']);
    Route::apiResource('exams', ExamResultController::class)->only(['index','store','update','destroy']);
    Route::get('/exam-departments', [ExamManagementController::class, 'departments']);
    Route::post('/exam-departments', [ExamManagementController::class, 'storeDepartment']);
    Route::put('/exam-departments/{department}', [ExamManagementController::class, 'updateDepartment']);
    Route::delete('/exam-departments/{department}', [ExamManagementController::class, 'destroyDepartment']);
    Route::apiResource('question-bank', QuestionBankController::class)->only(['index', 'store', 'show', 'update', 'destroy'])->parameters(['question-bank' => 'questionBankQuestion']);
    Route::get('/exam-templates', [ExamManagementController::class, 'templates']);
    Route::post('/exam-templates', [ExamManagementController::class, 'storeTemplate']);
    Route::put('/exam-templates/{template}', [ExamManagementController::class, 'updateTemplate']);
    Route::delete('/exam-templates/{template}', [ExamManagementController::class, 'destroyTemplate']);
    Route::get('/exam-templates/{template}/pdf', [ExamManagementController::class, 'downloadPdf']);
    Route::post('/exam-templates/{template}/start', [ExamManagementController::class, 'startSession']);
    Route::post('/exam-sessions/{session}/events', [ExamManagementController::class, 'event']);
    Route::post('/exam-sessions/{session}/answers', [ExamManagementController::class, 'answer']);
    Route::post('/exam-sessions/{session}/submit', [ExamManagementController::class, 'submit']);
    Route::apiResource('payments', PaymentController::class)->only(['index','store','update','destroy']);
    Route::get('/reports/summary', [ReportController::class, 'summary']);
    Route::get('/plugins', [PluginStoreController::class, 'index']);
    Route::get('/plugins/installed', [PluginStoreController::class, 'installed']);
    Route::post('/plugins/{plugin}/purchase', [PluginStoreController::class, 'purchase']);
    Route::post('/plugins/{plugin}/install', [PluginStoreController::class, 'install']);
    Route::delete('/plugins/{plugin}/install', [PluginStoreController::class, 'uninstall']);
});
